// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCAaKaZZaayvvL4mWftc8rGMs8GME3TQ',
    appId: '1:348336127326:web:7777988d2c620a8c61e3cf',
    messagingSenderId: '348336127326',
    projectId: 'benaiah-mobile-app',
    authDomain: 'benaiah-mobile-app.firebaseapp.com',
    storageBucket: 'benaiah-mobile-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApuukG5oCFqHcgB0sRmrpTUtDC-5MCsk',
    appId: '1:348336127326:android:5e2fe0169c0f13d361e3cf',
    messagingSenderId: '348336127326',
    projectId: 'benaiah-mobile-app',
    storageBucket: 'benaiah-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnnxGmSK3c4fR3C9uXUqqt4xHgV8cpJxU',
    appId: '1:348336127326:ios:40a18b9c96002b2161e3cf',
    messagingSenderId: '348336127326',
    projectId: 'benaiah-mobile-app',
    storageBucket: 'benaiah-mobile-app.appspot.com',
    iosBundleId: 'co.benaiah.benaiah-mobile-app',
  );
}
